# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-28 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('kısaltma', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Ogretmen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('brans', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ogretmen.Brans')),
            ],
        ),
    ]
