# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogretmen', '0002_auto_20161228_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brans',
            options={'ordering': ['ad', 'kısaltma'], 'verbose_name': 'Branş', 'verbose_name_plural': 'Branşlar'},
        ),
        migrations.AlterModelOptions(
            name='ogretmen',
            options={'ordering': ['ad', 'soyad'], 'verbose_name': 'Öğretmen', 'verbose_name_plural': 'Öğretmenler'},
        ),
    ]
