# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogretmen', '0003_auto_20170101_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogretmen',
            name='eposta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='ogretmen',
            name='isdihdam',
            field=models.CharField(choices=[('KADROLU', 'Kadrolu'), ('SOZLESMELI', 'Sözleşmeli'), ('UCRETLI', 'Ücretli')], default='KADROLU', max_length=20),
        ),
        migrations.AddField(
            model_name='ogretmen',
            name='tcno',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='ogretmen',
            name='telefon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
