# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ustyazi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ustyazi',
            options={'default_permissions': ('ekle', 'güncelle', 'sil', 'görüntüle')},
        ),
    ]
