# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-05 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(unique=True)),
                ('sinif', models.CharField(max_length=30)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('cinsiyet', models.CharField(choices=[('Erkek', 'Erkek'), ('Kız', 'Kız')], max_length=30)),
            ],
        ),
    ]
