# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0002_auto_20161115_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='sinif',
            field=models.CharField(max_length=50, verbose_name='Sınıf'),
        ),
    ]
